spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
security:
  oauth2:
    resource:
      filter-order: 3
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
---
spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/training
    username: lukaszandrzejewski
  jpa:
    hibernate:
      ddl-auto: update